sudo: required
services:
  - docker

# command to build
before_install:
  - docker build -t dockerid90/docker-react -f Dockerfile.dev .

# command to run test
script:
  - docker run -e CI=true dockerid90/docker-react npm run test -- --coverage

# deploy command
deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-west-2-306476627547"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"